### ISSUE TITLE
Not working on paper 1.8.8

### ISSUE THREAD

**Issue by TheDingOfTheHud** [Multiverse/Multiverse-Core#2553]
> [08:00:48 INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.2.2-b812
> [08:00:48 INFO]: [Multiverse-Core] §aWe are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
> [08:00:48 WARN]: [Multiverse-Core] Cannot load worlds.yml
> [08:00:48 INFO]: [Multiverse-Core] Loading World & Settings - 'world' - Env: NORMAL - Type: FLAT & seed: 0
> [08:00:48 ERROR]: Error occurred while enabling Multiverse-Core v4.2.2-b812 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/entity/Phantom
at com.onarandombox.MultiverseCore.utils.SimpleWorldPurger.killDecision(SimpleWorldPurger.java:152) ~[?:?]
at com.onarandombox.MultiverseCore.utils.SimpleWorldPurger.purgeWorld(SimpleWorldPurger.java:119) ~[?:?]
at com.onarandombox.MultiverseCore.utils.SimpleWorldPurger.purgeWorld(SimpleWorldPurger.java:197) ~[?:?]
at com.onarandombox.MultiverseCore.utils.SimpleWorldPurger.purgeWorld(SimpleWorldPurger.java:74) ~[?:?]
at com.onarandombox.MultiverseCore.MVWorld$SpawningPropertyValidator.validateChange(MVWorld.java:286) ~[?:?]
at com.onarandombox.MultiverseCore.MVWorld$SpawningPropertyValidator.validateChange(MVWorld.java:260) ~[?:?]
at com.onarandombox.serializationconfig.SerializationConfig.SerializationConfig.validate(SerializationConfig.java:893) ~[?:?]
at com.onarandombox.serializationconfig.SerializationConfig.SerializationConfig.setPropertyValue(SerializationConfig.java:443) ~[?:?]
at com.onarandombox.serializationconfig.SerializationConfig.SerializationConfig.setPropertyValue(SerializationConfig.java:368) ~[?:?]
at com.onarandombox.serializationconfig.SerializationConfig.SerializationConfig.setPropertyValue(SerializationConfig.java:353) ~[?:?]
at com.onarandombox.serializationconfig.SerializationConfig.SerializationConfig.setPropertyValueUnchecked(SerializationConfig.java:736) ~[?:?]
at com.onarandombox.MultiverseCore.WorldProperties.setAllowAnimalSpawn(WorldProperties.java:424) ~[?:?]
at com.onarandombox.MultiverseCore.MVWorld.setAllowAnimalSpawn(MVWorld.java:767) ~[?:?]
at com.onarandombox.MultiverseCore.MVWorld.validateEntitySpawns(MVWorld.java:195) ~[?:?]
at com.onarandombox.MultiverseCore.MVWorld.validateProperties(MVWorld.java:205) ~[?:?]
at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:94) ~[?:?]
at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:59) ~[?:?]
at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:509) ~[?:?]
at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:286) ~[?:?]
at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:228) ~[?:?]
at com.onarandombox.MultiverseCore.utils.WorldManager.loadDefaultWorlds(WorldManager.java:714) ~[?:?]
at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:306) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.Phantom
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
... 33 more
> [08:00:48 INFO]: [Multiverse-Core] Disabling Multiverse-Core v4.2.2-b812

Anyone know how to fix this?

**Comment by benwoo1110** [comment]
MC 1.8.x You will need to use an even older version of Multiverse - 2.5 should work (not the same as 2.5.0): https://dev.bukkit.org/projects/multiverse-core/files/898527

**Comment by TheDingOfTheHud** [comment]
ty
